name: Build BlorgFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_NAME: BlorgFS.sln
  ChocolateyUseWindowsCompression: 'true'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug]
        platform: [x64]
    name: Build ${{ matrix.config }} ${{ matrix.platform }}

    steps:
    - name: Detect if Dependabot
      id: is_dependabot
      run: echo "is_dependabot=${{ github.actor == 'dependabot[bot]' }}" >> $env:GITHUB_OUTPUT

    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        token: ${{ steps.is_dependabot.outputs.is_dependabot == 'true' && secrets.GH_DEPENDABOT_PAT || secrets.GH_PAT }}
        submodules: recursive

    - name: Get flatcc commit hash
      id: flatcc_hash
      run: |
        cd flatcc
        $hash = git rev-parse HEAD
        echo "flatcc_hash=$hash" >> $env:GITHUB_OUTPUT

    - name: Cache Flatcc build
      uses: actions/cache@v4
      with:
        path: | 
          flatcc\bin\Release
          flatcc\build\MSVC
        key: ${{ runner.os }}-flatcc-${{ steps.flatcc_hash.outputs.flatcc_hash }}

    - name: Install build tools
      if: steps.cache.outputs.cache-hit != 'true'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Build flatcc compiler
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          cd flatcc
          mkdir build\MSVC
          cd build\MSVC
          cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -G "Visual Studio 17 2022" ..\..
          cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 --build . --config Release

    - name: Create generated flatbuffer files
      run: flatcc\bin\Release\flatcc.exe -rv --common_reader schemas\metadata_flatbuffer.fbs

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ./packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Obtain WDK from Nuget
      run: nuget restore -PackagesDirectory ".\packages"

    - name: Build driver
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} /bl

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BlorgFS-${{ matrix.config }}-${{ matrix.platform }}
        path: |
          ${{ github.workspace }}/${{ matrix.platform }}/${{ matrix.config }}/**
          ${{ github.workspace }}/*.sys
          ${{ github.workspace }}/*.pdb
          ${{ github.workspace }}/*.inf
          ${{ github.workspace }}/*.cat
        retention-days: 5